export declare const list: any;
export declare const getById: any;
export declare const getByToken: any;
export declare const getByName: any;
export declare const getByClaimToken: any;
export declare const upsert: any;
export declare const updateStatus: any;
export declare const remove: any;
export declare const count: any;
